// ccboard/client/src/App.tsx
import { useState, useEffect } from "react";
import { Dashboard } from "./pages/Dashboard";
import { Session } from "./pages/Session";
import { CommandPalette } from "./components/shell/CommandPalette";
import { navLog } from "./lib/utils/logger";

export function App() {
  const [path, setPath] = useState(window.location.pathname);

  useEffect(() => {
    const onPop = () => {
      navLog.info("popstate →", window.location.pathname);
      setPath(window.location.pathname);
    };
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, []);

  const sessionMatch = path.match(/^\/session\/(\d+)$/);
  const pid = sessionMatch?.[1] ? Number(sessionMatch[1]) : null;

  navLog.debug("route", { path, pid });

  return (
    <>
      <CommandPalette />
      {pid ? <Session pid={pid} /> : <Dashboard />}
    </>
  );
}

// ccboard/client/src/App.svelte
<script lang="ts">
  import Dashboard from "./lib/pages/Dashboard.svelte";
  import Session from "./lib/pages/Session.svelte";
  import CommandPalette from "./lib/components/shell/CommandPalette.svelte";

  // Reactive path tracking — use a module-level setter so navigateTo can trigger updates
  let currentPath = $state(window.location.pathname);

  // Expose a global function for navigation
  (window as unknown as Record<string, unknown>).__ccboardNavigate = (path: string) => {
    window.history.pushState({}, "", path);
    currentPath = path;
  };

  // Also handle browser back/forward
  $effect(() => {
    const onPopState = () => { currentPath = window.location.pathname; };
    window.addEventListener("popstate", onPopState);
    return () => window.removeEventListener("popstate", onPopState);
  });

  // Derive route
  let route = $derived.by(() => {
    const sessionMatch = currentPath.match(/^\/session\/(\d+)$/);
    if (sessionMatch?.[1]) return { page: "session" as const, pid: Number(sessionMatch[1]) };
    return { page: "dashboard" as const, pid: 0 };
  });
</script>

<CommandPalette />

{#if route.page === "session"}
  <Session pid={route.pid} />
{:else}
  <Dashboard />
{/if}
