// ccboard/client/src/lib/components/session/actions/ActionsPane.svelte
<script lang="ts">
  import type { ActionEvent as ActionEvt, ActionStreamEvent } from "../../../types/sse-events";
  import { getActions } from "../../../services/api";
  import { createSSE } from "../../../services/sse";
  import ActionEvent from "./ActionEvent.svelte";
  import ActionDetailModal from "./ActionDetailModal.svelte";
  import { onMount } from "svelte";

  let { pid }: { pid: number } = $props();

  let events = $state<ActionEvt[]>([]);
  let selectedEvent = $state<ActionEvt | null>(null);
  let modalOpen = $state(false);
  let scrollEl: HTMLDivElement | undefined = $state();

  // Dedup for SSE events
  const seen = new Set<string>();
  function eventKey(e: ActionEvt): string {
    return `${e.tool}:${e.timestamp ?? ""}:${e.detail?.slice(0, 30) ?? ""}`;
  }

  function scrollToBottom() {
    if (scrollEl) scrollEl.scrollTop = scrollEl.scrollHeight;
  }

  async function loadHistorical() {
    try {
      const turns = await getActions(pid);
      for (const turn of turns) {
        for (const a of turn.actions) {
          if (a.type === "tool_use" && a.tool) {
            const evt: ActionEvt = {
              type: "action",
              tool: a.tool,
              detail: a.text ?? a.command ?? a.filePath ?? a.pattern ?? "",
              timestamp: a.timestamp,
              filePath: a.filePath,
              command: a.command,
              description: a.description,
              oldString: a.oldString,
              newString: a.newString,
              pattern: a.pattern,
              path: a.path,
            };
            const key = eventKey(evt);
            if (!seen.has(key)) {
              seen.add(key);
              events.push(evt);
            }
          }
        }
      }
      events = [...events]; // trigger reactivity
      setTimeout(scrollToBottom, 50);
    } catch (err) {
      console.error("Failed to load actions:", err);
    }
  }

  const sse = createSSE<ActionStreamEvent>(
    `/api/sessions/${pid}/action-stream`,
    (data) => {
      if (data.type === "action") {
        const key = eventKey(data);
        if (!seen.has(key)) {
          seen.add(key);
          events = [...events, data];
          // Cap at 500 events
          if (events.length > 500) events = events.slice(-400);
          setTimeout(scrollToBottom, 50);
        }
      }
    }
  );

  function openDetail(evt: ActionEvt) {
    selectedEvent = evt;
    modalOpen = true;
  }

  onMount(() => {
    loadHistorical();
    sse.connect();
    return () => sse.disconnect();
  });
</script>

<div class="pane-header">
  <span>Live Actions</span>
  <span class="action-count">{events.length}</span>
</div>

<div class="actions-scroll" bind:this={scrollEl}>
  <div class="spacer"></div>
  {#if events.length === 0}
    <div class="empty">waiting for agent activity<span class="cursor"></span></div>
  {:else}
    {#each events as evt}
      <ActionEvent event={evt} onclick={() => openDetail(evt)} />
    {/each}
  {/if}
</div>

<ActionDetailModal event={selectedEvent} open={modalOpen} onclose={() => { modalOpen = false; }} />

<style>
  .pane-header {
    padding: 6px 10px; font-size: 10px; text-transform: uppercase;
    letter-spacing: 1px; color: var(--text-dim);
    border-bottom: 1px solid var(--border); flex-shrink: 0;
    display: flex; justify-content: space-between; align-items: center;
  }
  .action-count { font-size: 9px; color: var(--text-dim); text-transform: none; }

  .actions-scroll {
    flex: 1; overflow-y: auto; min-height: 0;
    font-size: 11px; display: flex; flex-direction: column;
  }
  .spacer { flex: 1; }

  .empty { color: var(--text-dim); font-size: 11px; padding: 20px; text-align: center; }
  .cursor { animation: blink 1s step-end infinite; }
  @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
</style>

// ccboard/client/src/components/session/actions/ActionsPane.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import type { ActionEvent as ActionEventType } from "../../../lib/types/sse-events";
import type { ActionStreamEvent } from "../../../lib/types/sse-events";
import { getActions } from "../../../lib/services/api";
import { createSSE } from "../../../lib/services/sse";
import { apiLog, sseLog, renderLog } from "../../../lib/utils/logger";
import { ActionEvent } from "./ActionEvent";
import { ActionDetailModal } from "./ActionDetailModal";

const MAX_EVENTS = 500;
const INITIAL_TURNS = 20;

interface ActionsPaneProps {
  pid: number;
}

export function ActionsPane({ pid }: ActionsPaneProps) {
  const [events, setEvents] = useState<ActionEventType[]>([]);
  const [selected, setSelected] = useState<ActionEventType | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Load historical actions
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const turns = await getActions(pid);
        if (cancelled) return;
        const capped = turns.slice(-INITIAL_TURNS);
        const flat: ActionEventType[] = [];
        for (const turn of capped) {
          for (const a of turn.actions) {
            if (a.type === "tool_use" && a.tool) {
              flat.push({
                type: "action",
                tool: a.tool,
                detail: a.text || a.description || "",
                timestamp: a.timestamp,
                filePath: a.filePath,
                command: a.command,
                description: a.description,
                oldString: a.oldString,
                newString: a.newString,
                pattern: a.pattern,
                path: a.path,
              });
            }
          }
        }
        apiLog.debug("actions loaded", flat.length);
        setEvents(flat);
      } catch (err) {
        apiLog.warn("actions fetch failed", err);
      }
    })();
    return () => { cancelled = true; };
  }, [pid]);

  // SSE for real-time actions
  useEffect(() => {
    const sse = createSSE<ActionStreamEvent>(
      `/api/sessions/${pid}/action-stream`,
      (data) => {
        if (data.type === "action") {
          const evt = data as ActionEventType;
          sseLog.debug("action-stream event", evt.tool);
          setEvents((prev) => {
            const next = [...prev, evt];
            return next.length > MAX_EVENTS ? next.slice(-MAX_EVENTS) : next;
          });
        }
      }
    );
    sse.connect();
    return () => sse.disconnect();
  }, [pid]);

  // Auto-scroll
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [events.length]);

  const handleClick = useCallback((evt: ActionEventType) => {
    renderLog.debug("action detail", evt.tool);
    setSelected(evt);
    setModalOpen(true);
  }, []);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      <div
        style={{
          padding: "0.5rem 0.75rem",
          borderBottom: "1px solid var(--border)",
          fontFamily: "var(--font-heading)",
          fontSize: "0.8rem",
          letterSpacing: "0.1em",
          textTransform: "uppercase",
          color: "var(--orange)",
        }}
      >
        ACTIONS
        <span style={{ color: "var(--text-dim)", marginLeft: "0.5rem", fontSize: "0.7rem" }}>
          {events.length}
        </span>
      </div>

      <div ref={scrollRef} style={{ flex: 1, overflowY: "auto" }}>
        {events.length === 0 && (
          <div
            style={{
              padding: "1rem",
              fontFamily: "var(--font-body)",
              fontSize: "0.8rem",
              color: "var(--text-dim)",
              textAlign: "center",
            }}
          >
            No actions yet
          </div>
        )}
        {events.map((evt, i) => (
          <ActionEvent key={i} event={evt} onClick={() => handleClick(evt)} />
        ))}
      </div>

      <ActionDetailModal
        event={selected}
        open={modalOpen}
        onClose={() => setModalOpen(false)}
      />
    </div>
  );
}
