// ccboard/client/src/components/shared/Modal.tsx
import { useEffect, useCallback, useRef, type ReactNode } from "react";
import { renderLog } from "../../lib/utils/logger";

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  children: ReactNode;
}

export function Modal({ open, onClose, title, children }: ModalProps) {
  const overlayRef = useRef<HTMLDivElement>(null);

  const handleKey = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    },
    [onClose]
  );

  useEffect(() => {
    if (open) {
      renderLog.debug("Modal opened:", title);
      document.addEventListener("keydown", handleKey);
      return () => document.removeEventListener("keydown", handleKey);
    }
  }, [open, handleKey, title]);

  if (!open) return null;

  return (
    <div
      ref={overlayRef}
      onClick={(e) => {
        if (e.target === overlayRef.current) onClose();
      }}
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 5000,
        background: "var(--bg-overlay)",
        backdropFilter: "blur(4px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "2rem",
      }}
    >
      <div
        style={{
          background: "var(--bg-panel)",
          borderLeft: "3px solid var(--orange)",
          borderTop: "1px solid var(--border)",
          borderRight: "1px solid var(--border)",
          borderBottom: "1px solid var(--border)",
          maxWidth: "800px",
          width: "100%",
          maxHeight: "85vh",
          display: "flex",
          flexDirection: "column",
          position: "relative",
          overflow: "hidden",
        }}
      >
        {/* Corner brackets */}
        <div
          style={{
            position: "absolute",
            top: 0,
            right: 0,
            width: "20px",
            height: "20px",
            borderTop: "2px solid var(--orange)",
            borderRight: "2px solid var(--orange)",
            pointerEvents: "none",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: 0,
            left: "3px",
            width: "20px",
            height: "20px",
            borderBottom: "2px solid var(--orange)",
            borderLeft: "2px solid var(--orange)",
            pointerEvents: "none",
          }}
        />

        {/* Header */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "0.75rem 1rem",
            borderBottom: "1px solid var(--border)",
            fontFamily: "var(--font-heading)",
            fontSize: "1rem",
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "var(--orange)",
          }}
        >
          <span>{title}</span>
          <button
            onClick={onClose}
            style={{
              background: "none",
              border: "1px solid var(--border)",
              color: "var(--text)",
              cursor: "pointer",
              fontFamily: "var(--font-mono)",
              fontSize: "0.8rem",
              padding: "0.2rem 0.5rem",
            }}
          >
            ESC
          </button>
        </div>

        {/* Body */}
        <div
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "1rem",
          }}
        >
          {children}
        </div>
      </div>
    </div>
  );
}

// ccboard/client/src/lib/components/shared/Modal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let { open = false, onclose, children, title }: {
    open: boolean;
    onclose: () => void;
    children: Snippet;
    title?: string;
  } = $props();

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === e.currentTarget) onclose();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") onclose();
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-overlay" onclick={handleOverlayClick}>
    <div class="modal">
      <div class="modal-header">
        {#if title}
          <div class="modal-title">{title}</div>
        {/if}
        <button class="modal-close" onclick={onclose}>✕</button>
      </div>
      <div class="modal-body">
        {@render children()}
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    position: fixed; inset: 0;
    background: rgba(0, 0, 0, 0.6);
    z-index: 8000;
    display: flex; justify-content: center; align-items: flex-start;
    padding-top: 8vh;
  }

  :global([data-theme="light"]) .modal-overlay {
    background: rgba(0, 0, 0, 0.3);
  }

  .modal {
    width: 700px; max-width: 90vw; max-height: 80vh;
    background: var(--bg-card);
    border: 1px solid var(--border);
    display: flex; flex-direction: column;
  }

  .modal-header {
    display: flex; justify-content: space-between; align-items: center;
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }

  .modal-title {
    font-size: 11px; text-transform: uppercase;
    letter-spacing: 1px; color: var(--text-bright);
  }

  .modal-close {
    background: none; border: 1px solid var(--border);
    color: var(--text-dim); cursor: pointer;
    font-size: 10px; padding: 2px 8px;
    font-family: inherit;
  }
  .modal-close:hover { color: var(--text-bright); }

  .modal-body {
    flex: 1; overflow-y: auto; padding: 12px;
  }

  .modal-body::-webkit-scrollbar { width: 4px; }
  .modal-body::-webkit-scrollbar-track { background: transparent; }
  .modal-body::-webkit-scrollbar-thumb { background: var(--border); }
</style>
