// ccboard/client/src/lib/components/session/reviews/FindingItem.svelte
<script lang="ts">
  import type { Finding } from "../../../types/reports";
  import { escapeHtml } from "../../../utils/html";

  let { finding }: { finding: Finding } = $props();

  let severity = $derived((finding.severity ?? "low").toLowerCase());
  let location = $derived.by(() => {
    const loc = finding.location;
    if (!loc) {
      if (finding.file) return finding.line ? `${finding.file}:${finding.line}` : finding.file;
      return "";
    }
    if (typeof loc === "string") return loc;
    return loc.line ? `${loc.file}:${loc.line}` : loc.file;
  });
</script>

<div class="finding {severity}">
  <div class="finding-head">
    <span class="finding-severity">{severity}</span>
    {#if finding.confidence}
      <span class="finding-tag">CONF: {finding.confidence}</span>
    {/if}
    {#if typeof finding.impact === "string" && finding.impact.length <= 20}
      <span class="finding-tag">IMPACT: {finding.impact}</span>
    {/if}
    {#if location}
      <span class="finding-location">{location}</span>
    {/if}
  </div>

  {#if finding.title}
    <div class="finding-title">{finding.title}</div>
  {/if}

  {#if finding.description}
    <div class="finding-desc">{finding.description}</div>
  {/if}

  {#if typeof finding.impact === "string" && finding.impact.length > 20}
    <div class="finding-impact">Impact: {finding.impact}</div>
  {/if}

  {#if finding.resolution}
    <div class="finding-resolved">✓ {finding.resolution}</div>
  {/if}

  {#if finding.recommendation}
    <div class="finding-suggestion">→ {finding.recommendation}</div>
  {/if}
  {#if finding.suggestion}
    <div class="finding-suggestion">→ {finding.suggestion}</div>
  {/if}

  {#if finding.evidence}
    <div class="finding-evidence">{finding.evidence}</div>
  {/if}

  {#if finding.discrepancy}
    <div class="finding-discrepancy">{finding.discrepancy}</div>
  {/if}

  {#if finding.tags?.length}
    <div class="finding-tags">
      {#each finding.tags as tag}
        <span class="tag">{tag}</span>
      {/each}
    </div>
  {/if}
</div>

<style>
  .finding {
    padding: 8px 10px;
    background: var(--bg);
    margin-bottom: 4px;
    border-left: 2px solid var(--text-dim);
    font-size: 10px;
  }
  .finding.critical { border-left-color: var(--red-dim); }
  .finding.high { border-left-color: var(--red-dim); }
  .finding.medium { border-left-color: var(--amber-dim); }
  .finding.low { border-left-color: var(--text-dim); }

  .finding-head {
    display: flex; gap: 6px; align-items: center;
    margin-bottom: 4px; flex-wrap: wrap;
  }

  .finding-severity {
    font-size: 8px; text-transform: uppercase;
    letter-spacing: 1px; padding: 1px 4px;
    border: 1px solid currentColor;
  }
  .finding.critical .finding-severity { color: var(--red-dim); }
  .finding.high .finding-severity { color: var(--red-dim); }
  .finding.medium .finding-severity { color: var(--amber-dim); }

  .finding-tag {
    font-size: 8px; color: var(--text-dim);
    border: 1px solid var(--border); padding: 1px 4px;
    letter-spacing: 1px;
  }

  .finding-location {
    font-size: 9px; color: var(--cyan-dim);
    margin-left: auto;
  }

  .finding-title {
    font-size: 11px; color: var(--text-bright);
    margin-bottom: 3px; font-weight: 500;
  }

  .finding-desc { color: var(--text); margin-bottom: 3px; }
  .finding-impact { color: var(--amber-dim); margin-bottom: 3px; font-size: 9px; }
  .finding-resolved { color: var(--green-dim); margin-bottom: 3px; }
  .finding-suggestion { color: var(--text); margin-bottom: 3px; font-style: italic; }
  .finding-evidence {
    background: var(--bg-card); padding: 4px 6px;
    border-left: 1px solid var(--border);
    color: var(--text-dim); margin-top: 4px;
    font-family: 'JetBrains Mono', monospace; font-size: 9px;
    white-space: pre-wrap;
  }
  .finding-discrepancy { color: var(--red-dim); margin-top: 3px; }

  .finding-tags { margin-top: 3px; display: flex; gap: 2px; flex-wrap: wrap; }
  .tag {
    font-size: 8px; padding: 1px 4px;
    background: var(--bg); border: 1px solid var(--border);
    color: var(--text-dim);
  }
</style>

// ccboard/client/src/components/session/reviews/FindingItem.tsx
import type { Finding } from "../../../lib/types/reports";

interface FindingItemProps {
  finding: Finding;
}

const SEVERITY_COLORS: Record<string, string> = {
  critical: "var(--red)",
  high: "var(--red-dim)",
  warning: "var(--orange)",
  medium: "var(--orange-dim)",
  low: "var(--yellow-dim)",
  info: "var(--blue)",
  ok: "var(--green)",
};

function getSeverityColor(severity?: string): string {
  if (!severity) return "var(--text-dim)";
  return SEVERITY_COLORS[severity.toLowerCase()] || "var(--text-dim)";
}

export function FindingItem({ finding }: FindingItemProps) {
  const sevColor = getSeverityColor(finding.severity);

  const locationStr =
    typeof finding.location === "string"
      ? finding.location
      : finding.location
        ? `${finding.location.file}${finding.location.line ? `:${finding.location.line}` : ""}`
        : finding.file
          ? `${finding.file}${finding.line ? `:${finding.line}` : ""}`
          : null;

  const labelStyle: React.CSSProperties = {
    color: "var(--text-dim)",
    fontFamily: "var(--font-data)",
    fontSize: "0.65rem",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    marginTop: "0.3rem",
  };

  return (
    <div
      style={{
        borderLeft: `3px solid ${sevColor}`,
        padding: "0.5rem 0.75rem",
        marginBottom: "0.5rem",
        background: "rgba(0,0,0,0.15)",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.25rem" }}>
        {finding.severity && (
          <span
            style={{
              fontFamily: "var(--font-data)",
              fontSize: "0.65rem",
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              color: sevColor,
              background: "rgba(0,0,0,0.3)",
              padding: "0.1rem 0.4rem",
            }}
          >
            {finding.severity}
          </span>
        )}
        {finding.title && (
          <span
            style={{
              color: "var(--text-bright)",
              fontFamily: "var(--font-body)",
              fontSize: "0.8rem",
              fontWeight: 600,
            }}
          >
            {finding.title}
          </span>
        )}
      </div>

      {finding.description && (
        <div
          style={{
            color: "var(--text)",
            fontFamily: "var(--font-body)",
            fontSize: "0.8rem",
            lineHeight: 1.4,
            marginBottom: "0.25rem",
          }}
        >
          {finding.description}
        </div>
      )}

      {locationStr && (
        <>
          <div style={labelStyle}>LOCATION</div>
          <div
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "0.75rem",
              color: "var(--blue)",
            }}
          >
            {locationStr}
          </div>
        </>
      )}

      {finding.evidence && (
        <>
          <div style={labelStyle}>EVIDENCE</div>
          <div
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "0.7rem",
              color: "var(--text)",
              whiteSpace: "pre-wrap",
              background: "rgba(0,0,0,0.2)",
              padding: "0.3rem",
              marginTop: "0.15rem",
            }}
          >
            {finding.evidence}
          </div>
        </>
      )}

      {finding.suggestion && (
        <>
          <div style={labelStyle}>SUGGESTION</div>
          <div
            style={{
              fontFamily: "var(--font-body)",
              fontSize: "0.75rem",
              color: "var(--green)",
              marginTop: "0.1rem",
            }}
          >
            {finding.suggestion}
          </div>
        </>
      )}

      {finding.tags && finding.tags.length > 0 && (
        <div style={{ display: "flex", gap: "0.3rem", marginTop: "0.3rem", flexWrap: "wrap" }}>
          {finding.tags.map((tag, i) => (
            <span
              key={i}
              style={{
                fontFamily: "var(--font-data)",
                fontSize: "0.6rem",
                letterSpacing: "0.06em",
                color: "var(--text-dim)",
                border: "1px solid var(--border-neutral)",
                padding: "0.05rem 0.35rem",
              }}
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
